### ISSUE TITLE
Good Morning Cron: Mems -> General

### ISSUE THREAD

**Issue by judegiordano** [BillyP-Bot/billybot-backend#20]
Feature request `WOQPRPTDFCVYOAJGRLZV`
request to move Good Morning Rock and Roll from mems channel to general

**Comment by flogan** [comment]
lets just kill toad

**Comment by flogan** [comment]
@judegiordano @cdleveille Looking for input on whether or not we want to pull trig on poor ole toad

**Comment by cdleveille** [comment]
Kill him.
